### PR TITLE
Fix TypeScript typings

### PR DESCRIPTION
**Pull request by Richienb**
Correctly define how the database class is exported.

### CODE REVIEW

**Comment by Richienb** [comment]
// @kochman

**Comment by RedGuy12** [comment]
Bruh 

#14

**Comment by Richienb** [comment]
> Bruh
> 
> #14

This PR improves on that one with a more succicient exporting syntax.

**Comment by louy** [comment]
if anyone is struggling until this is merged, here's a temporary solution:
```ts
const Client = require("@replit/database");
import type {Client as replClient} from "@replit/database"
const dbClient: replClient = new Client();
```

**Comment by masad-frost** [comment]
resolved in #52

**Pull request closed without merging**
