### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by josh-codes**
Please review this pull request, 

The new version contains much needed improvements
- Built using Axios instead of fetch
- Support for importing without using the default export
- Sanitized input
- License change MIT -> LGPL-3.0
- Updating many keys is faster now

### CODE REVIEW

**Comment by josh-codes** [comment]
@jnnnthnn please review my PR

**Comment by jeremypress** [comment]
hey @josh-codes, thanks for your PR! Since this is essentially a rewrite of the library, can you break these up into smaller chunks? For example, linting rules / package changes could come first, then core library / readme changes, and then we can review the license changes? Thank you!

**Comment by josh-codes** [comment]
> hey @josh-codes, thanks for your PR! Since this is essentially a rewrite of the library, can you break these up into smaller chunks? For example, linting rules / package changes could come first, then core library / readme changes, and then we can review the license changes? Thank you!

It would be hard to. The license change makes this hard, I chose lgpl because I heard it was good, however I am happy

**Comment by jeremypress** [comment]
regarding the license. If we don't have a good reason to change it, let's not! We can always revisit that later

Regarding splitting up PRs, yes!
1. It makes it much much easier to test and review
2. if there are any issues with one portion of the change, that can be safely reverted while still keeping the other changes you made

**Comment by josh-codes** [comment]
Sorry if I’m being an idiot, but if there is a mistake, can’t we just revert the commit?

**Pull request closed without merging**
